name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with coverage (don't fail on error)
      run: |
        mkdir -p reports
        pytest tests \
          --junitxml=reports/junit.xml \
          --cov=my_app \
          --cov-report=xml:reports/coverage.xml
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: junit-report
        path: reports/junit.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: reports/coverage.xml

  publish:
    runs-on: ubuntu-latest
    needs: test_and_coverage

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: checkout artefacts
      uses: actions/download-artifact
    - name: Publish test annotations
      uses: dorny/test-reporter@v1
      with:
        name: Pytest Tests
        path: reports/junit.xml
        reporter: java-junit
        fail-on-error: false

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: reports/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }} # si nécessaire (public repo n'en a pas besoin)
