name: test secret
on:
  workflow_dispatch:

jobs:
 test1:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Call secret
        run: echo my secret is ${{ secrets.MYTOKEN1}}
  
 test2:
    runs-on: ubuntu-latest
    env:
      MYSECRET: ${{ secrets.MYTOKEN1 }}
    steps:
      - name: call 2 
        run: echo my secret again $MYSECRET

